# Generated by Django 6.0.7 on 2026-08-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cartuser_paymentmethod_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='PaidAt',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='paidAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
